version: '3.8'

services:
  app:
    build: .
    container_name: flowershop_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: unless-stopped

  queue:
    build: .
    container_name: flowershop_queue
    command: php artisan queue:work --sleep=3 --tries=3
    volumes:
      - .:/var/www
    depends_on:
      - app
    restart: unless-stopped

  schedule:
    build: .
    container_name: flowershop_schedule
    command: php artisan schedule:work
    volumes:
      - .:/var/www
    depends_on:
      - app
    restart: unless-stopped